FORMAT: 1A
HOST: 

# SPA register with email API

|created at|author|
|:---:|:---:|
|2022-02-15|Tran Anh Quang|

## Update history

|no|date|author|change section|change log|
|:---:|:---:|:---:|:---:|:---|

## Login API [POST /api/login]

### Description

*  login with google, facebook, phone number

+ Request (application/json)

    + Headers
        ```
        X-Requested-With: XMLHttpRequest
        ```

+ Response 200 (application/json)

     + Body
        [
            {
                "_id": "61ec0684f4685bb55021868a",
                "uid": "cbZOJYaANbYhTl5UKYEYh9AqW2A3",
                "role": 1,
                "verify": true,
                "name": "kaio",
                "email": "songoku2192@gmail.com",
                "photoURL": "https://www.google.com/imgres?imgurl=https%3A%2F%2Fletdiv.com%2Fwp-content%2Fuploads%2F2021%2F06%2Freact-native-course.jpg&imgrefurl=https%3A%2F%2Fletdiv.com%2Fkhoa-hoc-react-native%2F&tbnid=fNDCY99t7gaO2M&vet=12ahUKEwiWydHe5YH2AhWa7WEKHaxKDBUQMygDegUIARC-AQ..i&docid=msTZg0A-nASefM&w=1024&h=576&q=image%20online%20react%20native&ved=2ahUKEwiWydHe5YH2AhWa7WEKHaxKDBUQMygDegUIARC-AQ",
                "phoneNumber": "0987362624",
                "address": "Từ Liêm - Hà Nội",
                "gender": "nam",
                "createdAt": {
                    "$date": "2022-01-22T13:28:39.794Z"
                },
                "updatedAt": {
                    "$date": "2022-01-22T13:28:39.794Z"
                },
                "__v": 0
            }
        ]

